/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Music Collection API
 * The Music Collection API description
 * OpenAPI spec version: 1.0
 */

export * from "./song";
export * from "./songControllerCreateBody";
export * from "./songControllerDelete200";
export * from "./songControllerFindAllParams";
export * from "./songControllerUpdateBody";
