/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Music Collection API
 * The Music Collection API description
 * OpenAPI spec version: 1.0
 */

export type SongControllerFindAllParams = {
  /**
   * Search term to filter songs by name or artist
   */
  search?: string;
};
