/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Music Collection API
 * The Music Collection API description
 * OpenAPI spec version: 1.0
 */

export type SongControllerCreateBody = {
  /** The artist of the song */
  artist: string;
  /** The audio file (mp3, wav, ogg) - max 100MB */
  audioFile?: Blob;
  /** The cover image file (jpg, jpeg, png) - max 10MB */
  coverImage: Blob;
  /** The name of the song */
  name: string;
};
